/*
 * gpi Corporate API
 * Move your app forward with the gpi Corporate API
 *
 * OpenAPI spec version: 2.0.2-sandbox
 * Contact: Li.JIE@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.tracker.trackerg4c.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.tracker.trackerg4c.model.GetCorporatePaymentTransactionsResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ISO 20022 JSON Schema GetCorporatePaymentTransactionsResponse (camt.a08.002.01) Generated by SWIFT Standards 2018-07-12 05:30:53
 */
@ApiModel(description = "ISO 20022 JSON Schema GetCorporatePaymentTransactionsResponse (camt.a08.002.01) Generated by SWIFT Standards 2018-07-12 05:30:53")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T10:36:31.126-05:00")
public class CamtA0800201 {
  @SerializedName("get_corporate_payment_transactions_response")
  private GetCorporatePaymentTransactionsResponse getCorporatePaymentTransactionsResponse = null;

  public CamtA0800201 getCorporatePaymentTransactionsResponse(GetCorporatePaymentTransactionsResponse getCorporatePaymentTransactionsResponse) {
    this.getCorporatePaymentTransactionsResponse = getCorporatePaymentTransactionsResponse;
    return this;
  }

   /**
   * Get getCorporatePaymentTransactionsResponse
   * @return getCorporatePaymentTransactionsResponse
  **/
  @ApiModelProperty(value = "")
  public GetCorporatePaymentTransactionsResponse getGetCorporatePaymentTransactionsResponse() {
    return getCorporatePaymentTransactionsResponse;
  }

  public void setGetCorporatePaymentTransactionsResponse(GetCorporatePaymentTransactionsResponse getCorporatePaymentTransactionsResponse) {
    this.getCorporatePaymentTransactionsResponse = getCorporatePaymentTransactionsResponse;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CamtA0800201 camtA0800201 = (CamtA0800201) o;
    return Objects.equals(this.getCorporatePaymentTransactionsResponse, camtA0800201.getCorporatePaymentTransactionsResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getCorporatePaymentTransactionsResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CamtA0800201 {\n");
    
    sb.append("    getCorporatePaymentTransactionsResponse: ").append(toIndentedString(getCorporatePaymentTransactionsResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

