/*
 * gpi Corporate API
 * Move your app forward with the gpi Corporate API
 *
 * OpenAPI spec version: 2.0.2-sandbox
 * Contact: Li.JIE@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.tracker.trackerg4c.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.tracker.trackerg4c.model.DateTimePeriodDetails;
import com.swift.tracker.trackerg4c.model.PaymentStatus4;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Contains the request to obtain information on the corporate status of one or more payment transactions.
 */
@ApiModel(description = "Contains the request to obtain information on the corporate status of one or more payment transactions.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T10:36:31.126-05:00")
public class GetCorporatePaymentTransactionsRequest {
  @SerializedName("my_institution")
  private List<String> myInstitution = new ArrayList<String>();

  @SerializedName("uetr")
  private String uetr = null;

  @SerializedName("time_window")
  private DateTimePeriodDetails timeWindow = null;

  @SerializedName("transaction_status")
  private List<PaymentStatus4> transactionStatus = null;

  @SerializedName("maximum_number")
  private String maximumNumber = null;

  @SerializedName("more")
  private String more = null;

  public GetCorporatePaymentTransactionsRequest myInstitution(List<String> myInstitution) {
    this.myInstitution = myInstitution;
    return this;
  }

  public GetCorporatePaymentTransactionsRequest addMyInstitutionItem(String myInstitutionItem) {
    this.myInstitution.add(myInstitutionItem);
    return this;
  }

   /**
   * Specifies the institution which payments are requested.
   * @return myInstitution
  **/
  @ApiModelProperty(required = true, value = "Specifies the institution which payments are requested.")
  public List<String> getMyInstitution() {
    return myInstitution;
  }

  public void setMyInstitution(List<String> myInstitution) {
    this.myInstitution = myInstitution;
  }

  public GetCorporatePaymentTransactionsRequest uetr(String uetr) {
    this.uetr = uetr;
    return this;
  }

   /**
   * Contains the unique end to end transaction reference.   Format is lowercase separated by hyphens.
   * @return uetr
  **/
  @ApiModelProperty(value = "Contains the unique end to end transaction reference.   Format is lowercase separated by hyphens.")
  public String getUetr() {
    return uetr;
  }

  public void setUetr(String uetr) {
    this.uetr = uetr;
  }

  public GetCorporatePaymentTransactionsRequest timeWindow(DateTimePeriodDetails timeWindow) {
    this.timeWindow = timeWindow;
    return this;
  }

   /**
   * Time window for this institution to which the search applies.
   * @return timeWindow
  **/
  @ApiModelProperty(value = "Time window for this institution to which the search applies.")
  public DateTimePeriodDetails getTimeWindow() {
    return timeWindow;
  }

  public void setTimeWindow(DateTimePeriodDetails timeWindow) {
    this.timeWindow = timeWindow;
  }

  public GetCorporatePaymentTransactionsRequest transactionStatus(List<PaymentStatus4> transactionStatus) {
    this.transactionStatus = transactionStatus;
    return this;
  }

  public GetCorporatePaymentTransactionsRequest addTransactionStatusItem(PaymentStatus4 transactionStatusItem) {
    if (this.transactionStatus == null) {
      this.transactionStatus = new ArrayList<PaymentStatus4>();
    }
    this.transactionStatus.add(transactionStatusItem);
    return this;
  }

   /**
   * Specifies the status of a transaction, in a coded form.
   * @return transactionStatus
  **/
  @ApiModelProperty(value = "Specifies the status of a transaction, in a coded form.")
  public List<PaymentStatus4> getTransactionStatus() {
    return transactionStatus;
  }

  public void setTransactionStatus(List<PaymentStatus4> transactionStatus) {
    this.transactionStatus = transactionStatus;
  }

  public GetCorporatePaymentTransactionsRequest maximumNumber(String maximumNumber) {
    this.maximumNumber = maximumNumber;
    return this;
  }

   /**
   * Indicates the maximum number of entries returned.
   * @return maximumNumber
  **/
  @ApiModelProperty(value = "Indicates the maximum number of entries returned.")
  public String getMaximumNumber() {
    return maximumNumber;
  }

  public void setMaximumNumber(String maximumNumber) {
    this.maximumNumber = maximumNumber;
  }

  public GetCorporatePaymentTransactionsRequest more(String more) {
    this.more = more;
    return this;
  }

   /**
   * Contains the token to get the next set of responses.
   * @return more
  **/
  @ApiModelProperty(value = "Contains the token to get the next set of responses.")
  public String getMore() {
    return more;
  }

  public void setMore(String more) {
    this.more = more;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporatePaymentTransactionsRequest getCorporatePaymentTransactionsRequest = (GetCorporatePaymentTransactionsRequest) o;
    return Objects.equals(this.myInstitution, getCorporatePaymentTransactionsRequest.myInstitution) &&
        Objects.equals(this.uetr, getCorporatePaymentTransactionsRequest.uetr) &&
        Objects.equals(this.timeWindow, getCorporatePaymentTransactionsRequest.timeWindow) &&
        Objects.equals(this.transactionStatus, getCorporatePaymentTransactionsRequest.transactionStatus) &&
        Objects.equals(this.maximumNumber, getCorporatePaymentTransactionsRequest.maximumNumber) &&
        Objects.equals(this.more, getCorporatePaymentTransactionsRequest.more);
  }

  @Override
  public int hashCode() {
    return Objects.hash(myInstitution, uetr, timeWindow, transactionStatus, maximumNumber, more);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporatePaymentTransactionsRequest {\n");
    
    sb.append("    myInstitution: ").append(toIndentedString(myInstitution)).append("\n");
    sb.append("    uetr: ").append(toIndentedString(uetr)).append("\n");
    sb.append("    timeWindow: ").append(toIndentedString(timeWindow)).append("\n");
    sb.append("    transactionStatus: ").append(toIndentedString(transactionStatus)).append("\n");
    sb.append("    maximumNumber: ").append(toIndentedString(maximumNumber)).append("\n");
    sb.append("    more: ").append(toIndentedString(more)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

