/*
 * gpi Corporate API
 * Move your app forward with the gpi Corporate API
 *
 * OpenAPI spec version: 2.0.2-sandbox
 * Contact: Li.JIE@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.tracker.trackerg4c.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.tracker.trackerg4c.model.PaymentTransaction75;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Contains the response to the request to obtain information on the corporate status of one or more payment transactions.
 */
@ApiModel(description = "Contains the response to the request to obtain information on the corporate status of one or more payment transactions.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T10:36:31.126-05:00")
public class GetCorporatePaymentTransactionsResponse {
  @SerializedName("payment_transaction")
  private List<PaymentTransaction75> paymentTransaction = new ArrayList<PaymentTransaction75>();

  @SerializedName("total_number")
  private String totalNumber = null;

  @SerializedName("more")
  private String more = null;

  public GetCorporatePaymentTransactionsResponse paymentTransaction(List<PaymentTransaction75> paymentTransaction) {
    this.paymentTransaction = paymentTransaction;
    return this;
  }

  public GetCorporatePaymentTransactionsResponse addPaymentTransactionItem(PaymentTransaction75 paymentTransactionItem) {
    this.paymentTransaction.add(paymentTransactionItem);
    return this;
  }

   /**
   * Contains details on the payment transaction.
   * @return paymentTransaction
  **/
  @ApiModelProperty(required = true, value = "Contains details on the payment transaction.")
  public List<PaymentTransaction75> getPaymentTransaction() {
    return paymentTransaction;
  }

  public void setPaymentTransaction(List<PaymentTransaction75> paymentTransaction) {
    this.paymentTransaction = paymentTransaction;
  }

  public GetCorporatePaymentTransactionsResponse totalNumber(String totalNumber) {
    this.totalNumber = totalNumber;
    return this;
  }

   /**
   * Contains the total number of returned result entries.
   * @return totalNumber
  **/
  @ApiModelProperty(required = true, value = "Contains the total number of returned result entries.")
  public String getTotalNumber() {
    return totalNumber;
  }

  public void setTotalNumber(String totalNumber) {
    this.totalNumber = totalNumber;
  }

  public GetCorporatePaymentTransactionsResponse more(String more) {
    this.more = more;
    return this;
  }

   /**
   * Contains a token to obtain the next set of responses. It indicates whether there are more results to retrieve, what timestamp to start from and how many more result entries are to be retrieved.
   * @return more
  **/
  @ApiModelProperty(value = "Contains a token to obtain the next set of responses. It indicates whether there are more results to retrieve, what timestamp to start from and how many more result entries are to be retrieved.")
  public String getMore() {
    return more;
  }

  public void setMore(String more) {
    this.more = more;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporatePaymentTransactionsResponse getCorporatePaymentTransactionsResponse = (GetCorporatePaymentTransactionsResponse) o;
    return Objects.equals(this.paymentTransaction, getCorporatePaymentTransactionsResponse.paymentTransaction) &&
        Objects.equals(this.totalNumber, getCorporatePaymentTransactionsResponse.totalNumber) &&
        Objects.equals(this.more, getCorporatePaymentTransactionsResponse.more);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentTransaction, totalNumber, more);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporatePaymentTransactionsResponse {\n");
    
    sb.append("    paymentTransaction: ").append(toIndentedString(paymentTransaction)).append("\n");
    sb.append("    totalNumber: ").append(toIndentedString(totalNumber)).append("\n");
    sb.append("    more: ").append(toIndentedString(more)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

