/*
 * gpi Corporate API
 * Move your app forward with the gpi Corporate API
 *
 * OpenAPI spec version: 2.0.2-sandbox
 * Contact: Li.JIE@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.tracker.trackerg4c.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.tracker.trackerg4c.model.PaymentReason2Code;
import com.swift.tracker.trackerg4c.model.TransactionIndividualStatus5Code;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Indicates the payment transaction status and optionally the reason for that status. 
 */
@ApiModel(description = "Indicates the payment transaction status and optionally the reason for that status. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T10:36:31.126-05:00")
public class PaymentStatus4 {
  @SerializedName("status")
  private TransactionIndividualStatus5Code status = null;

  @SerializedName("reason")
  private PaymentReason2Code reason = null;

  public PaymentStatus4 status(TransactionIndividualStatus5Code status) {
    this.status = status;
    return this;
  }

   /**
   * Reason for the status, as published in an external reason code list.
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Reason for the status, as published in an external reason code list.")
  public TransactionIndividualStatus5Code getStatus() {
    return status;
  }

  public void setStatus(TransactionIndividualStatus5Code status) {
    this.status = status;
  }

  public PaymentStatus4 reason(PaymentReason2Code reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Provides more details on the status in process.
   * @return reason
  **/
  @ApiModelProperty(value = "Provides more details on the status in process.")
  public PaymentReason2Code getReason() {
    return reason;
  }

  public void setReason(PaymentReason2Code reason) {
    this.reason = reason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentStatus4 paymentStatus4 = (PaymentStatus4) o;
    return Objects.equals(this.status, paymentStatus4.status) &&
        Objects.equals(this.reason, paymentStatus4.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, reason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentStatus4 {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

