/*
 * gpi Corporate API
 * Move your app forward with the gpi Corporate API
 *
 * OpenAPI spec version: 2.0.2-sandbox
 * Contact: Li.JIE@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.tracker.trackerg4c.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Provides the reason for a specific Payment Status.
 */
@JsonAdapter(PaymentReason2Code.Adapter.class)
public enum PaymentReason2Code {
  
  G005("G005"),
  
  G006("G006"),
  
  G001("G001");

  private String value;

  PaymentReason2Code(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentReason2Code fromValue(String text) {
    for (PaymentReason2Code b : PaymentReason2Code.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PaymentReason2Code> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentReason2Code enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentReason2Code read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentReason2Code.fromValue(String.valueOf(value));
    }
  }
}

