/*
 * gpi Corporate API
 * Move your app forward with the gpi Corporate API
 *
 * OpenAPI spec version: 2.0.2-sandbox
 * Contact: Li.JIE@swift.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.tracker.trackerg4c.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Specifies the status of a single payment transaction.
 */
@JsonAdapter(TransactionIndividualStatus5Code.Adapter.class)
public enum TransactionIndividualStatus5Code {
  
  RJCT("RJCT"),
  
  ACSP("ACSP"),
  
  ACCC("ACCC");

  private String value;

  TransactionIndividualStatus5Code(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TransactionIndividualStatus5Code fromValue(String text) {
    for (TransactionIndividualStatus5Code b : TransactionIndividualStatus5Code.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TransactionIndividualStatus5Code> {
    @Override
    public void write(final JsonWriter jsonWriter, final TransactionIndividualStatus5Code enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TransactionIndividualStatus5Code read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TransactionIndividualStatus5Code.fromValue(String.valueOf(value));
    }
  }
}

